POST http://{{nbi_url}}/nbi/cpe/add
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "id": "5f9e7e70-6839-7148-2636-2450-1058db32",
  "sn": "xxxxxx",
  "device_id": "",
  "attrs": null
}

###

POST http://{{nbi_url}}/nbi/cpe/update
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "sn": "xxxxxx",
  "attrs": {
    "uprate": 1048576
  }
}

###

POST http://{{nbi_url}}/nbi/cpe/query
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{}

###


GET http://{{nbi_url}}/nbi/cpe/query
authorization: Bearer {{nbi_token}}

###


GET http://{{nbi_url}}/nbi/cpe/delete?sn=xxxxxx
authorization: Bearer {{nbi_token}}

###
