POST http://{{nbi_url}}/nbi/data/test/add
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "collname": "test",
  "data": {
    "_id": "12345",
    "name": "xxxxxx"
  }
}

###

POST http://{{nbi_url}}/nbi/data/test/update
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "_id": "12345",
  "collname": "test",
  "data": {
    "name": "xxxxxx222"
  }
}

###

POST http://{{nbi_url}}/nbi/data/test/query
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "collname": "test",
  "querymap": {
    "name": "xxxxxx"
  }
}

###


GET http://{{nbi_url}}/nbi/data/test/get?collname=test&_id=12345
authorization: Bearer {{nbi_token}}

###


GET http://{{nbi_url}}/nbi/data/query?collname=test&count=0
authorization: Bearer {{nbi_token}}

###

GET http://{{nbi_url}}/nbi/data/customer/options?optionname=name
authorization: Bearer {{nbi_token}}

###


GET http://{{nbi_url}}/nbi/data/delete?collname=test&_id=12345
authorization: Bearer {{nbi_token}}

###
