POST http://{{nbi_url}}/nbi/subscribe/add
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDQ0Nzc4NzcsImx2bCI6ImRlZmF1bHQiLCJ1aWQiOiJhZG1pbiIsInVzciI6ImFkbWluIn0.JXSIrTZUzFAByqk8Pl2280zkqvtETb1iX4Vovw14Gx0

{
  "id": "5f9ead80-2621-ad46-7036-27ad-2ec3e7a9",
  "vpe_sids": null,
  "profile": {
    "domain": "N/A",
    "interim_interval": 0,
    "addr_pool": "N/A",
    "active_num": 1,
    "mfa_status": "disabled",
    "up_rate": 1048576,
    "down_rate": 1048576,
    "limit_policy": "N/A",
    "up_limit_policy": "N/A",
    "down_limit_policy": "N/A"
  },
  "realname": "test",
  "email": "test@teamsacs.com",
  "username": "test01",
  "password": "888888",
  "mfa_status": "disabled",
  "mfa_secret": "N/A",
  "ipaddr": "N/A",
  "macaddr": "N/A",
  "vlanid1": 0,
  "vlanid2": 0,
  "bind_mac": 0,
  "bind_vlan": 0,
  "status": "Enabled",
  "remark": "Test user"
}

###

POST http://{{nbi_url}}/nbi/subscribe/update
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDQ0Nzc4NzcsImx2bCI6ImRlZmF1bHQiLCJ1aWQiOiJhZG1pbiIsInVzciI6ImFkbWluIn0.JXSIrTZUzFAByqk8Pl2280zkqvtETb1iX4Vovw14Gx0

{
  "username": "test01",
  "realname": "test2",
  "profile": {
    "up_rate": 10485760
  }
}

###

POST http://{{nbi_url}}/nbi/subscribe/query
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDQ0Nzc4NzcsImx2bCI6ImRlZmF1bHQiLCJ1aWQiOiJhZG1pbiIsInVzciI6ImFkbWluIn0.JXSIrTZUzFAByqk8Pl2280zkqvtETb1iX4Vovw14Gx0

{}

###


GET http://{{nbi_url}}/nbi/subscribe/query
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDQ0Nzc4NzcsImx2bCI6ImRlZmF1bHQiLCJ1aWQiOiJhZG1pbiIsInVzciI6ImFkbWluIn0.JXSIrTZUzFAByqk8Pl2280zkqvtETb1iX4Vovw14Gx0

###


GET http://{{nbi_url}}/nbi/subscribe/delete?username=test01
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDQ0Nzc4NzcsImx2bCI6ImRlZmF1bHQiLCJ1aWQiOiJhZG1pbiIsInVzciI6ImFkbWluIn0.JXSIrTZUzFAByqk8Pl2280zkqvtETb1iX4Vovw14Gx0

###
