POST http://{{nbi_url}}/nbi/vpe/add
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "id": "5f9ecba9-13d9-9140-8527-2f1b-fbbe9f57",
  "sn": "yyyyyy",
  "identifier": "tradtest",
  "name": "tradtest",
  "ipaddr": "ipaddr",
  "secret": "secret",
  "vendor_code": "2011",
  "coa_port": 3799
}
###

POST http://{{nbi_url}}/nbi/vpe/update
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{
  "sn": "yyyyyy",
  "ipaddr": "127.0.0.1"
}

###

POST http://{{nbi_url}}/nbi/vpe/query
Content-Type: application/json
authorization: Bearer {{nbi_token}}

{}

###


GET http://{{nbi_url}}/nbi/vpe/query
authorization: Bearer {{nbi_token}}

###


GET http://{{nbi_url}}/nbi/vpe/delete?sn=yyyyyy
authorization: Bearer {{nbi_token}}

###
